# Generated by Django 2.2.4 on 2019-08-18 09:58

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.URLField()),
                ('code', models.TextField()),
                ('username', models.IntegerField(default=0)),
                ('password', models.IntegerField(default=1)),
                ('index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('pages', models.ManyToManyField(to='website.Page')),
            ],
            managers=[
                ('objects', website.models.DomainManager()),
            ],
        ),
    ]
